variable "vpc_cidr" {}
variable "public_subnet_1_cidr" {}
variable "public_subnet_1_az" {}
variable "public_subnet_2_cidr" {}
variable "public_subnet_2_az" {}
variable "private_subnet_1_cidr" {}
variable "private_subnet_1_az" {}
variable "private_subnet_2_cidr" {}
variable "private_subnet_2_az" {}